name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setting up python
        uses: actions/setup-python@v5

      - name: Install pytest
        run: pip install pytest

      - name: Setting up go
        uses: actions/setup-go@v6

      - name: Install sql-migrate tool
        run: go install github.com/rubenv/sql-migrate/...@latest

      - name: Start services
        working-directory: 03-image-server
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          REGION: ${{ secrets.REGION }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_CONN_STRING: ${{ secrets.DB_CONN_STRING }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          BROKER_URI: ${{ secrets.BROKER_URI }}
          QUEUE_NAME: ${{ secrets.QUEUE_NAME }}
          REPLY_QUEUE_NAME: ${{ secrets.REPLY_QUEUE_NAME }}
        run: docker compose up -d --build --wait --wait-timeout 120

      - name: Print logs if something went wrong
        if: failure()
        run: docker compose logs

      - name: Run integration tests
        run: pytest
